apiVersion: v1
kind: Service
metadata:
  name: np-nginx-svc
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort
