global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    basic_auth:
      username: admin
      password: admin
    scrape_interval: 5s
    static_configs:
      - targets: 
        - nodeexporter:9100
        labels: 
          env: node1
      - targets:
        - 10.1.2.32:9100
        labels:       
          env: node2
      
    metric_relabel_configs:
        - source_labels: [instance]
          regex: '(.*):9100'
          replacement: '$1'
          target_label: instance


  - job_name: 'cadvisor'
    basic_auth:
      username: admin
      password: admin
    scrape_interval: 5s
    static_configs:
      - targets: 
        - cadvisor:8080
        labels:
          env: node1
      - targets:
        - 10.1.2.32:8080
        labels:
          env: node2

    metric_relabel_configs:
        - source_labels: [instance]
          regex: '(.*):8080'
          replacement: '$1'
          target_label: instance


  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'alertmanager'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['grafana:3000']

# node02
#  - job_name: 'nodeexporter2'
#    basic_auth:
#      username: admin
#      password: admin
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['10.1.2.32:9100']
#  - job_name: 'cadvisor2'
#    basic_auth:
#      username: admin
#      password: admin
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['10.1.2.32:8080']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'
