---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_listen_ip: "{{ hostvars[ 'clickhouse-01' ].ansible_default_ipv4.address }}"