resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    workers

    [managers:children]
    active
    standby

    [active]
    manager-01.netology.yc ansible_host=${yandex_compute_instance.manager[0].network_interface.0.nat_ip_address}

    [standby]
    manager-02.netology.yc ansible_host=${yandex_compute_instance.manager[1].network_interface.0.nat_ip_address}
    manager-03.netology.yc ansible_host=${yandex_compute_instance.manager[2].network_interface.0.nat_ip_address}

    [workers]
    worker-01.netology.yc ansible_host=${yandex_compute_instance.worker[0].network_interface.0.nat_ip_address}
    worker-02.netology.yc ansible_host=${yandex_compute_instance.worker[1].network_interface.0.nat_ip_address}
    worker-03.netology.yc ansible_host=${yandex_compute_instance.worker[2].network_interface.0.nat_ip_address}
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.manager[0],
    yandex_compute_instance.manager[1],
    yandex_compute_instance.manager[2],
    yandex_compute_instance.worker[0],
    yandex_compute_instance.worker[1],
    yandex_compute_instance.worker[2]
  ]
}
