---
- name: Test module role
  hosts: localhost
  collections:
    - my_own_collection.yandex_cloud_elk
  tasks:
    - name: import role
      ansible.builtin.import_role:
        name: createfile-role
