apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lesson
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/describe"]
  verbs: ["get", "watch", "list"]