---

all:
  hosts:
    jenkins-master-01:
      ansible_host: 130.193.48.171
    jenkins-agent-01:
      ansible_host: 158.160.43.186
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
            jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
