---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
    - name: Create table
      ansible.builtin.command: "clickhouse-client -q 'create table logs.local_log
        (file String, hostname String, message String, timestamp DateTime) Engine=Log;'"
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc !=57
      changed_when: create_table.rc == 0
#- name: Install Vector from role
#  hosts: vektor
#  roles:
#    - vector-role
#- name: Install Vector
#  hosts: vector
#  tasks:
#    - name: Install Vector
#      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash -s -- -y"
#      register: script_output
#    - name: Run Docker debug
#      debug: var=script_output.stdout_lines
- name: Install Vector manual
  hosts: vector
  handlers:
    - name: restarted vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - block:
      - name: Get vector distrib
        ansible.builtin.get_url:
          url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
          dest: "{{ home_dir }}/vector-{{ vector_version }}.tar.gz"
      - name: Create root directory
        ansible.builtin.file:
          path: "{{ home_dir }}/vector-{{ vector_version }}"
          state: directory
      - name: Extract vector
        ansible.builtin.unarchive:
          src: "{{ home_dir }}/vector-{{ vector_version }}.tar.gz"
          dest: "{{ home_dir }}/vector-{{ vector_version }}/"
          extra_opts: [--strip-components=2]
          remote_src: yes
    - block:
      - name: Copy vector to bin with owner and permissions
        ansible.builtin.copy:
          src: "{{ home_dir }}/vector-{{ vector_version }}/bin/vector"
          dest: /usr/bin/vector
          mode: '0755'
          remote_src: true
      - name: Configure vector.service from template
        ansible.builtin.template:
          src: vector.service.j2
          dest: /etc/systemd/system/vector.service
          mode: 0644
        tags:
          - vector_service
      - name: create config dir for vector
        ansible.builtin.file:
          path: "{{ vector_config_dir }}"
          state: directory
          mode: 0644
      - name: Configure vector from template
        ansible.builtin.template:
          src: vector.yml.j2
          dest: "{{ vector_config_dir }}/vector.yml"
          mode: 0644
      - name: Create data directory
        ansible.builtin.file:
          path: "{{ vector_config.data_dir }}"
          state: directory
      become: true
      notify: restarted vector service
    - name: Flush handlers
      meta: flush_handlers
