apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rwtarget }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.frontPath }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: frontend-svc-{{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
      - path: {{ .Values.ingress.backPath }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: backend-svc-{{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}