apiVersion: v1
kind: Service
metadata:
  name: frontend-svc-{{ .Release.Name }}
spec:
  selector:
    app: frontend-{{ .Release.Name }}
  ports:
    - name: http-{{ .Release.Name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc-{{ .Release.Name }}
spec:
  selector:
    app: backend-{{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
