---
- block:
  - name: Get lighthouse from git
    ansible.builtin.git:
      repo: 'https://github.com/VKCOM/lighthouse.git'
      dest: "{{ lighthouse_home_dir }}"
    when: not ansible_check_mode
  - name: Configure nginx for lighthouse
    ansible.builtin.template:
      src: lighthouse.conf.j2
      dest: "{{ nginx_config_dir }}/conf.d/default.conf"
  become: true
  notify: restarted nginx service
- name: Flush handlers
  meta: flush_handlers
