{
 "title": "Netology",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "vCPU count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Used root fs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (100 * ((avg_over_time(node_memory_MemFree_bytes{instance=~\"$node\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\"$node\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"$node\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[5m])))"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (node_load1{instance=~\"$node\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"$node\"}))",
     "legendFormat": "LA1 host: {{instance}}"
    },
    {
     "expr": "(avg by(instance) (node_load5{instance=~\"$node\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"$node\"}))",
     "legendFormat": "LA5 host: {{instance}}"
    },
    {
     "expr": "(avg by(instance) (node_load15{instance=~\"$node\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"$node\"}))",
     "legendFormat": "LA15 host: {{instance}}"
    }
   ]
  }
 ]
}