name: ex5
on: workflow_dispatch

env:
  tf_path: HW07_ter_05_team/src/ex2/hw_terraform

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
#      - name: Setup TFLint
#        uses: terraform-linters/setup-tflint@v3.0.0
        
#      - name: Checkov GitHub Action
#        uses: bridgecrewio/checkov-action@v12.1347.0
        
      - name: tests
        run: |
          cd ${{ env.tf_path }} 
          terraform init -backend-config="bucket=${{ secrets.BUCKET }} access_key=${{ secrets.ACCESS_KEY }} secret_key=${{ secrets.SECRET_KEY }} dynamodb_endpoint=${{ secrets.DYNAMODB_ENDPOINT }} dynamodb_table=${{ secrets.DYNAMODB_ENDPOINT }}" 
#          tflint --init
#          tflint -f compact
#          checkov -d ./
          
          
      
