name: ex5
on: workflow_dispatch

env:
  tf_path: HW07_ter_05_team/src/ex2/hw_terraform

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
            
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ${{ env.tf_path }}
        
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3.0.0        
               
      - name: Terraform init
        run: |
          cd ${{ env.tf_path }} 
          terraform init -var token=${{ secrets.YC_TOKEN }} -var cloud_id=${{ secrets.CLOUD_ID }} -var folder_id=${{ secrets.FOLDER_ID }} \
            -backend-config="bucket=${{ vars.BUCKET }}" -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SECRET_KEY }}" -backend-config="dynamodb_endpoint=${{ vars.DYNAMODB_ENDPOINT }}"\
            -backend-config="dynamodb_table=${{ vars.DYNAMODB_TABLE }}" 
        
      - name: check
        run: |
          tflint --init
          tflint --chdir=${{ env.tf_path }} -f compact


         
          
      
